local cmain = cold_system

local COLD_OVERLAY = nil
local COLD_OVERLAY_WND = nil
local overlay_tmr = 0

function activate_cold_overlay()

	local hud = get_hud()

	if hud == nil then
		return
	end

	hud:AddCustomStatic("cold_overlay")

	COLD_OVERLAY = hud:GetCustomStatic("cold_overlay")

	if COLD_OVERLAY == nil then
		return
	end

	COLD_OVERLAY_WND = COLD_OVERLAY:wnd()

	if COLD_OVERLAY_WND == nil then
		return
	end

	COLD_OVERLAY_WND:Show(false)

end

function update_cold_overlay()
	local tg = time_global()

	if overlay_tmr > tg then
		return
	end

	overlay_tmr = tg + 500

	if COLD_OVERLAY_WND == nil then
		return
	end

	if not cold_system_mcm.get_config("ppe") then
		COLD_OVERLAY_WND:Show(false)
		return
	end

	if not cmain or not cmain.cold or not cmain.cold.val then
		return
	end

	local delta = cmain.cold.val / cmain.max_cold

	local overlay_power = (delta - 0.7) / 0.73
	overlay_power = clamp(overlay_power, 0, 1)

	overlay_power = overlay_power ^ 1.5

	if overlay_power <= 0 then
		COLD_OVERLAY_WND:Show(false)
		return
	end

	COLD_OVERLAY_WND:Show(true)

	local alpha = math.floor(overlay_power * 255)
	local clr = GetARGB(alpha, 255, 255, 255)

	COLD_OVERLAY_WND:SetTextureColor(clr)

end

function deactivate_cold_overlay()

	local hud = get_hud()

	if hud and COLD_OVERLAY then
		hud:RemoveCustomStatic("cold_overlay")
	end

	COLD_OVERLAY = nil
	COLD_OVERLAY_WND = nil
end

function on_game_start()

	RegisterScriptCallback("actor_on_first_update", activate_cold_overlay)
	RegisterScriptCallback("actor_on_update", update_cold_overlay)
	RegisterScriptCallback("actor_on_net_destroy", deactivate_cold_overlay)
	RegisterScriptCallback("actor_on_before_death", deactivate_cold_overlay)

end